url: https://www.vrmoment.net   # with the https protocol
enforce_ssl: www.vrmoment.net   # without any protocol

# For example, my configuration is this:
url: https://vrmoment.net
enforce_ssl: vrmoment.net
